import Head from 'next/head'
import Politica from '../components/politicaComponents'

export default function Home() {
  return (
    <>
      <Head>
        <title>Grupo HP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Politica />
      <h1 className='text-red-500'>Hello World!</h1>
    </>
  )
}